remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-sitemap
title: Yann's ME/CFS Site
description: Yann's ME/CFS Site
github:
  is_project_page: false
google_analytics: G-Y16SM6V3QE
