name: Generate xml sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
          token: ${{ secrets.PAT }} # Use a secret token with the necessary permissions

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Generate the sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://www.me-cfs.github.io/
          additional-extensions: md

      - name: Commit and push
        run: |
          if [[ `git status --porcelain sitemap.xml` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add sitemap.xml
            git commit -m "Automated sitemap update" sitemap.xml
            git push
          fi

  update-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Replace .md with .html in sitemap.xml
        run: |
          sed -i 's/\.md/\.html/g' sitemap.xml

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sitemap.xml
          git commit -m "Update sitemap to reflect .html extensions" || echo "No changes to commit"
          git push
