name: Update Personal News RSS Feed

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-rss-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install rss-parser xml2js

      - name: Run update script
        run: node news/rss/community_update.js
        env:
          FEED_CONFIG_PATH: '../../yann/personalhost/newsrssfeed/feedlist.js'
          LOCAL_FILE: 'yann/personalhost/newsrssfeed/news.xml'
          MAX_ITEMS: 200

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes if any
        run: |
          git add yann/personalhost/newsrssfeed/news.xml

          # Check for changes and commit if there are any
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update RSS feed"
            git push origin HEAD:main
          fi
        env:
          PAT_TOKEN: ${{ secrets.PATTOKEN }}